In [2]:
import numpy as np

In [3]:
# Create an array
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [4]:
#Checking dimension
a.ndim

1

In [9]:
# 2D array
b = np.array([[1,2,3],[4,5,6]])
print(b)
b.ndim  #check the dimension

[[1 2 3]
 [4 5 6]]


2

In [17]:
# 3D array
c = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(c)
c.ndim  #check the dimension

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


3

### Zero's and One's 

In [20]:
var=np.zeros(10)
var

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
var1=np.ones(7)
var1

array([1., 1., 1., 1., 1., 1., 1.])

In [22]:
np.ones((3,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [28]:
np.zeros((2,5,3))  # (noOfArray, row, Column)

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

# functions

In [64]:
var3 = np.array([22,33,44,777,9])
var3

array([ 22,  33,  44, 777,   9])

In [65]:
var4 = np.array([22,33,44,9])
var4

array([22, 33, 44,  9])

In [66]:
type(var3)

numpy.ndarray

In [67]:
var3.argmax()  #max value in index position

4

In [71]:
var3.argmin()  #min value in index position

4

In [68]:
var4.argmax()  #max value in index position

3

In [70]:
var4.argmin()  #min value in index position

3

In [72]:
var3[3]

777

In [73]:
var4[2]

44

In [85]:
var4

array([22, 33, 44,  9])

In [86]:
var4[1:3]

array([33, 44])

In [87]:
var4[0:-1]

array([22, 33, 44])

In [88]:
var4[::-1]

array([ 9, 44, 33, 22])

In [96]:
var4

array([22., 33., 44.,  9.])

# Array

In [98]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [99]:
arr.size

5

In [100]:
arr.dtype

dtype('int32')

In [102]:
#Create 2D Arrays

arr1 = np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [103]:
arr1.ndim

2

In [104]:
arr1.size

6

In [106]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [116]:
np.arange(12).reshape(4,3) 

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [109]:
np.arange(12).reshape(6,2)  # reshape value will be multiple otherwise it will show error

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [110]:
a.max()

11

In [111]:
a.min()

0

In [114]:
arr

array([1, 2, 3, 4, 5])

In [113]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

# Transpose

In [119]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [118]:
b=a.reshape(6,2)
b

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

# Stacking

In [122]:
arr4 = np.arange(10).reshape(2,5)
arr4

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [123]:
arr5 = np.arange(20).reshape(4,5)
arr5

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [125]:
np.vstack((arr4,arr5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [128]:
arr4

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [127]:
arr6 = np.arange(12).reshape(2,6)
arr6

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [130]:
aa = np.array([1, 2, 3])
bb = np.array([4, 5, 6])
np.vstack((aa,bb))

array([[1, 2, 3],
       [4, 5, 6]])